baseConfig:
  searchDirectory: "./"
  ignoreCase: false

directoryNaming:
  allowHyphens: true
  allowUnderscores: false
  mustBeLowercase: true

fileNaming:
  allowHyphens: true
  allowUnderscores: true
  mustBeLowercase: true

ignoreFormats:
  - "\\.log$"
  - "\\.env$"
  - "README\\.md$"
  - "_test\\.go$"
  - "\\.md$"
  - LICENSE

ignoreDirectories:
  - "vendor"
  - ".git"
  - "node_modules"
  - "logs"
  - "CHANGELOG"
  - "components"
  - "_output"
  - "tools/openim-web"
  - "CHANGELOG"
  - "examples/Test_directory"

fileTypeSpecificNaming:
  ".yaml":
    allowHyphens: true
    allowUnderscores: false
    mustBeLowercase: true
  ".go":
    allowHyphens: false
    allowUnderscores: true
    mustBeLowercase: true
